/*******************************************************************************
// Copyright (c) 2017 All Right Reserved
// THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY 
// KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
// NON-DISTRIBUTABLE: WITHOUT PRIOR WRITTEN PERMISSION FROM AUTHER THIS CODE
// ITS LOGIC OR ANY PART OF IT IS NOT REPRODUCABLE. 
// -----------------------------------------------------------------------------
// Author:          Sunil Kumar Sirangi
// File Name:       LocationWrapper 
// Summary:         Wrapper Class for IODS Controller
// Created On:      08-18-2017
*******************************************************************************/
public class LocationWrapper{// Wrapper class to hold location input information
    public string locationName {get; set;}
    public string address1 {get; set;}
    public string address2 {get; set;}
    public string country {get; set;}
    public string city {get; set;}
    public string state {get; set;}
    public string zip {get; set;}
    public string contactName {get; set;}
    public string email {get; set;}
    public string phone {get; set;}
    public string phoneext {get; set;}
    public string alternateContactName {get; set;}
    public string alternateEmail {get; set;}
    public string alternatePhone {get; set;}
    public string alternatePhoneext {get; set;}
    public id locationid {get; set;}
}